### ISSUE TITLE
Masking issue

### ISSUE THREAD

**Issue by superManhee** [AstrOOnauta/react-native-international-phone-number#102]
thx for your service!

when i use first 0,
i think masking was wrong...
and the allow maximum length seems to be different.

in my case,
<img width="329" alt="스크린샷 2024-12-11 오전 10 13 57" src="https://github.com/user-attachments/assets/fb7b3e1d-7b67-4889-8204-e784a96823bf">
<img width="328" alt="스크린샷 2024-12-11 오전 10 14 08" src="https://github.com/user-attachments/assets/522ceb9a-f545-4e69-a8a5-b1eb1188d144">

And i using allowZeroAfterCallingCode option,
but is fail....

**Comment by AstrOOnauta** [comment]
Hello @superManhee 

Use the props `allowZeroAfterCallingCode={false}` and the input will format the number without the 0 at the start.
