### ISSUE TITLE
Fixing Korean Mobile Number Format

### ISSUE THREAD

**Issue by y-solb** [AstrOOnauta/react-native-international-phone-number#103]
Correct:
![스크린샷 2024-12-11 오전 10 39 52](https://github.com/user-attachments/assets/a1841a60-312b-42b1-8cc8-592044d21552)

Incorrect:
![스크린샷 2024-12-11 오전 10 40 16](https://github.com/user-attachments/assets/e43af851-dd5f-4de7-8d83-43e24d04b27f)

The Korean format is 000 0000 0000.
However, while 222 2222 2222 works, it seems the format breaks when a 0 is added at the beginning.
Could you fix this?

Because in Korea, the mobile phone format is 010 1234 5678.
Thank you 💛

**Comment by AstrOOnauta** [comment]
Hey @y-solb let me know: do korean number phone allow same mask XXX XXXX XXXX with 0 or not at start after calling code?

**Comment by superManhee** [comment]
when allowed ZERO, XXX XXXX XXXX,
If not allowed ZERO, XX XXXX XXXX

thx for service!

**Comment by AstrOOnauta** [comment]
@superManhee  Thanks for your contribution! Next version this will be up.

**Comment by superManhee** [comment]
@AstrOOnauta Thx!

**Comment by AstrOOnauta** [comment]
I release a new version fixing this issue. So, please, update your lib for the latest version v.0.8.4.

🚀 AstrOOnauta 🚀
