### ISSUE TITLE
Custom modal design change ?

### ISSUE THREAD

**Issue by arirah** [AstrOOnauta/react-native-international-phone-number#11]
How can change custom modal styles? Any idea?

**Comment by arirah** [comment]
I need to change the font for a custom modal

**Comment by AstrOOnauta** [comment]
Hey @arirah 

The lib doesn't support customising the country picker modal, not for now...

🚀 AstrOOnauta 🚀

**Comment by AstrOOnauta** [comment]
@arirah

Now, you can custom the modal styles (usying the props `modalStyle`). To read more about this, visit the [documentation](https://github.com/AstrOOnauta/react-native-international-phone-number#custom-lib-styles).

Please, update the lib `react-native-international-phone-number` to `v0.5.3` and enjoy.

🚀 AstrOOnauta 🚀
