### ISSUE TITLE
Sending `onAnimatedValueUpdate` with no listeners registered.

### ISSUE THREAD

**Issue by arossoftware** [AstrOOnauta/react-native-international-phone-number#13]
When you try to search amongst countries list the right country, and you type it fast - you get `Sending onAnimatedValueUpdate with no listeners registered.` error, which is, in my case, reloads emulator build and mobile app itself.

Could you please see if you have the same? let me know if you need more details!

Thank you for your efforts!

**Comment by AstrOOnauta** [comment]
Hi @arossoftware 

I try reproduce this error and I cannot...
Please, can you give me more infomation? Print of the error? Share your code? 

Waiting for your reply

🚀 AstrOOnauta 🚀

**Comment by arossoftware** [comment]
Hi @AstrOOnauta 

Okay, looks like it was some problem in the development code, on TestFlight everything works and not crashing

Thanks!
