### ISSUE TITLE
Get International number format

### ISSUE THREAD

**Issue by dlenskyi** [AstrOOnauta/react-native-international-phone-number#14]
Hi @AstrOOnauta 

It would be also great to have a function on ref to get the full international number (including country code numbers)

**Comment by AstrOOnauta** [comment]
Hey @dlenskyi thanks for your request!
I've made a note of it and will implement it in a future version..

🚀 AstrOOnauta 🚀

**Comment by AstrOOnauta** [comment]
@dlenskyi sorry for delay.

I updated the lib and I added the field `fullPhoneNumber` inside the useRef callback for get the `full international number (including country code numbers)` that you suggested.

Use:
`phoneInputRef.current?.fullPhoneNumber`

Please, update the lib `react-native-international-phone-number` to `v0.5.3` and enjoy.

🚀 AstrOOnauta 🚀

**Comment by dlenskyi** [comment]
Hi @AstrOOnauta 

Amazing!

Thank you a lot 🔥
