### ISSUE TITLE
maxLength input

### ISSUE THREAD

**Issue by arirah** [AstrOOnauta/react-native-international-phone-number#16]
How to re set maxLength ?

**Comment by arirah** [comment]
Ok found the solution 
`customMask={['####` #####', '##### #####']}`

But need more specific details [here](https://github.com/AstrOOnauta/react-native-international-phone-number#custom-phone-mask)

**Comment by AstrOOnauta** [comment]
Hey @arirah 

You can use the normal textInput prop `maxLength` to do this. Check the example:

```
<PhoneInput
          value={inputValue}
          onChangePhoneNumber={setInputValue}
          selectedCountry={selectedCountry}
          onChangeSelectedCountry={setSelectedCountry}
          maxLength={4}   <--- ADD THIS
        />
```

🚀 AstrOOnauta 🚀

**Comment by arirah** [comment]
> Hey @arirah
> 
> You can use the normal textInput prop `maxLength` to do this. Check the example:
> 
> ```
> <PhoneInput
>           value={inputValue}
>           onChangePhoneNumber={setInputValue}
>           selectedCountry={selectedCountry}
>           onChangeSelectedCountry={setSelectedCountry}
>           maxLength={4}   <--- ADD THIS
>         />
> ```
> 
> 🚀 AstrOOnauta 🚀

You are right !
