### ISSUE TITLE
Flags doesnt shows on windows.

### ISSUE THREAD

**Issue by igorbojk** [AstrOOnauta/react-native-international-phone-number#18]
Unfortunately, flag emojis are not displayed on windows.
How can i fix it?
I found solution like
https://lepture.com/en/2022/windows-country-flags-emoji
But you didnt provide the possibility to change fontFamily for flag element

MACos
<img width="471" alt="Screenshot 2023-10-04 at 11 22 40" src="https://github.com/AstrOOnauta/react-native-international-phone-number/assets/14841207/7439d456-b5a7-43e3-9534-3f5c14641a96">
Windows
<img width="484" alt="Screenshot 2023-10-04 at 11 23 08" src="https://github.com/AstrOOnauta/react-native-international-phone-number/assets/14841207/3987a771-4963-490c-831c-b709c8bcdc07">

**Comment by AstrOOnauta** [comment]
Hey @igorbojk, thanks for your issue!


Sorry for this. I will study this case and I will get a solution soon...

🚀 AstrOOnauta 🚀

**Comment by AstrOOnauta** [comment]
@igorbojk  update for the new version (v0.6.0) and read the [new documentation for config the support to RN Web](https://github.com/AstrOOnauta/react-native-international-phone-number#additional-config-to-web).

Please try again and let me know if it worked.

🚀 AstrOOnauta 🚀

**Comment by jlora-mck** [comment]
Hey @AstrOOnauta im having the same issue here, im using react native windows (latest version) and i cant see the flags (i copied and pasted the .woff2 file to my assets in the Asset folder in the c# code but no luck) also the documentation you linked above is no longer available
