### ISSUE TITLE
Default value does not work for all numbers

### ISSUE THREAD

**Issue by VikasShashidhar** [AstrOOnauta/react-native-international-phone-number#19]
Hello. First of all, great library - easy to use and customise. I've been able to do most of what I've been wanting to with the library.

However, I am running into an issue when trying to set the default value. It doesn't work for all phone numbers. For ex., if you check the Snack here - https://snack.expo.dev/@vikas.shashidhar/phone-input-default-value, you'll notice that the default value has an Australian phone number which is perfectly valid. But, the component breaks.

<img width="1678" alt="image" src="https://github.com/AstrOOnauta/react-native-international-phone-number/assets/27778544/53f31fb8-4a65-4678-a3c3-18f205b6dd75">

Can you please help? Thanks.

**Comment by AstrOOnauta** [comment]
Hey @VikasShashidhar, sorry for this.
I will see this case soon...thanks for share it!

**Comment by VikasShashidhar** [comment]
No worries @AstrOOnauta. Thanks and let me know if you need help reproducing it.

**Comment by AstrOOnauta** [comment]
@VikasShashidhar I studied your case and fixed it in the newest lib version.

Please, update the lib version to v0.6.1 in your project and enjoy!!

🚀AstrOOnauta 🚀

**Comment by VikasShashidhar** [comment]
Thanks a ton @AstrOOnauta!
