### ISSUE TITLE
Select a default country

### ISSUE THREAD

**Issue by alic-xc** [AstrOOnauta/react-native-international-phone-number#2]
Hi Guys,

Thanks for putting forth this package, it has helped me in my project. 
Actually, I don't know how to add a default country.

Any help will be appreciated.

**Comment by AstrOOnauta** [comment]
Hey @alic-xc !

Nice to know that the lib [react-native-international-phone-number](https://github.com/AstrOOnauta/react-native-international-phone-number) helps you in some way.

About your issue, nice point!
The v0.4.3 not support this, but I released a next version that support a feat **add a default country**.
Please update the lib version to **v0.4.4** and read the next point in the docs to resolve your issue:

https://github.com/AstrOOnauta/react-native-international-phone-number#custom-default-flag

🚀AstrOOnauta 🚀
