### ISSUE TITLE
Custom translations

### ISSUE THREAD

**Issue by mcelikx** [AstrOOnauta/react-native-international-phone-number#21]
Hi, i've implemented this package into my project. I like it. But it doesn't support Turkish language :( Also i couldn't find custom translations. Is there a way to implement custom translations for placeholders ?

**Comment by AstrOOnauta** [comment]
@mcelikx sorry for my late answer...

For now, this lib dont support Turkish Language, sorry (but, you can help us translating the countries and placeholders... and doing a PR :) ). 

I studied your case about `implement custom placeholders` and I do on the new lib version.

So..please, update for the new version (v0.6.2) and read the [new documentation for add custom placeholders/messages](https://github.com/AstrOOnauta/react-native-international-phone-number#custom-placeholdersmessages).

Please try again and let me know if it worked.

🚀 AstrOOnauta 🚀
