### ISSUE TITLE
placeholderTextColor cannot be configured

### ISSUE THREAD

**Issue by Rowb** [AstrOOnauta/react-native-international-phone-number#22]
If you enter any color there, the color will change to a lighter one, but I would like to customize the color

**Comment by AstrOOnauta** [comment]
Hey @Rowb , sorry about this...

Please, update for the new version (v0.6.3) and try again...

🚀 AstrOOnauta 🚀

**Comment by Rowb** [comment]
Thank you very much!

**Comment by ser-emejia** [comment]
Hello, is there a way to remove the placeholder? I do not want to display it in my input
Thank you so much for this amazing library 🚀 🚀

**Comment by AstrOOnauta** [comment]
@ser-emejia add the next props into PhoneInput component: `placeholder=' '` (a blank space)
