### ISSUE TITLE
Style props not working

### ISSUE THREAD

**Issue by NextVertex-Flo** [AstrOOnauta/react-native-international-phone-number#23]
phoneInputStyles and modalStyles not working -> visual still the same in my app, nothing new happened
My code :
`<PhoneInput
                    value={phoneNumber}
                    onChangePhoneNumber={handleInputPhoneNumber}
                    selectedCountry={selectedCountry}
                    onChangeSelectedCountry={handleSelectedCountry}
                    phoneInputStyles={{
                        container: { backgroundColor: 'red', borderWidth: 1, borderStyle: 'solid', borderColor: '#F3F3F3'},
                        flagContainer: { borderTopLeftRadius: 7, borderBottomLeftRadius: 7, backgroundColor: '#808080', justifyContent: 'center',},
                        flag: {},
                        callingCode: { fontSize: 16, fontWeight: 'bold', color: '#F3F3F3', },
                        input: { color: '#F3F3F3', },
                    }}
                    modalStyles={{
                        modal: { backgroundColor: 'red', borderWidth: 1,},
                        backdrop: {},
                        divider: {backgroundColor: 'red',},
                        countriesList: {},
                        searchInput: {borderRadius: 8,borderWidth: 1,borderColor: '#F3F3F3',color: '#F3F3F3',backgroundColor: '#333333',paddingHorizontal: 12,height: 46,},
                        countryButton: {borderWidth: 1,borderColor: '#F3F3F3',backgroundColor: '#666666',marginVertical: 4,paddingVertical: 0,},
                        noCountryText: {},
                        noCountryContainer: {},
                        flag: {color: 'red',fontSize: 20,},
                        callingCode: {color: '#F3F3F3',},
                        countryName: {color: '#F3F3F3',},
                      }}
                />`

**Comment by AstrOOnauta** [comment]
@NextVertex-Flo sorry about this...

I fixed this issue on the next version...so, please, update your lib react-native-international-phone-number to `v0.6.4` and enjoy...


🚀 AstrOOnauta 🚀

**Comment by NextVertex-Flo** [comment]
Thanks a lot for your answer, I will take a look soon :)
