### ISSUE TITLE
Bad format for french number

### ISSUE THREAD

**Issue by LaGregance** [AstrOOnauta/react-native-international-phone-number#25]
Hi, thanks for this very useful package !

Unfortunately, I run into a little issue for French number (maybe it can impact others country but not sure).

Usually in France, phone number are generally written in any of the following formats:
 - `+33 6 12 34 56 78`
 - `+33 06 12 34 56 78`

I notice two things:
1. The first "0" is optional, but in your package it's forbidden
2. French number are formatted like American number (with number grouped by 3 instead of 2, in my example `+33 612 345 678`)

Is there a way to fix this ?

**Comment by LaGregance** [comment]
I just submitted a PR for this : https://github.com/AstrOOnauta/react-native-international-phone-number/pull/26

**Comment by AstrOOnauta** [comment]
@LaGregance Thanks!! I aproved your PR with this adjustments...its will be up on new version soon!

**Comment by AstrOOnauta** [comment]
@LaGregance I release a new version with your contribution...thanks

So, please update your lib to latest `v0.6.5`
