### ISSUE TITLE
**Issue: ❌ Invalid Cameroonian Phone Number Format**

### ISSUE THREAD

**Issue by Chips-Analytics-Kevin** [AstrOOnauta/react-native-international-phone-number#28]
**Description:**
The current phone number input field does not support the valid format for Cameroonian phone numbers, which consist of 9 digits (e.g., 694 645 415). Despite the correct format, it cannot be entered in the field.

**Request:**
I would like to request the option for users to customize the number of characters themselves. Alternatively, consider implementing a real-time validation API that checks the phone number based on the country.

**Note:**
The library is good overall, but this enhancement is necessary for usability.

**Best regards,**
Dissang Tenkam

**Comment by AstrOOnauta** [comment]
Hey  @Chips-Analytics-Kevin thanks for your issue and your review...

Actually this lib dont support validation (only if you use a tercery lib for this, like google-libphonenumber)...but it will...

For now, I updated the Cameroon phone masks with this 9 digits...so, please, update the `react-native-international-phone-number` to latest version `v0.6.5`...

🚀 AstrOOnauta 🚀

**Comment by Chips-Analytics-Kevin** [comment]
Thank you , your are the Best!!

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
