### ISSUE TITLE
I cant use showOnly 

### ISSUE THREAD

**Issue by erdincakdogan** [AstrOOnauta/react-native-international-phone-number#29]
Hello,

    "react-native-international-phone-number": "^0.4.12",
I m using this version and my using time is like a below

<PhoneInput
  value={inputValue}
  onChangePhoneNumber={handleInputValue}
  defaultCountry="TR"
  showOnly={['BR', 'PT', 'CA', 'US']}
  selectedCountry={selectedCountry}
  onChangeSelectedCountry={handleSelectedCountry}
  containerStyle={{
    flexDirection: "row",
    alignItems: "center", 
    borderBottomColor: "#ccc",
    borderBottomWidth: 1,
    paddingBottom: 8,
    marginBottom: 25,
  }}
  inputStyle={{
    flex: 1,
    paddingVertical: 0,
    marginLeft: 10,
    color: "black",
  }}
  flagContainerStyle={{
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 7,
    backgroundColor: "#808080",
    justifyContent: "center",
    marginLeft: 10,
    marginTop: 4 
  }}
/>

What is the problem about showOnly. I just want to use TR,DE

**Comment by AstrOOnauta** [comment]
Hey @erdincakdogan ..this feature `showOnly` is only available from v0.6.1.

So, please, update your lib version and read the actual documentation if you have any problem or break ;)

🚀 AstrOOnauta 🚀
