### ISSUE TITLE
Madagascar mask phone number format incorrect

### ISSUE THREAD

**Issue by PaulOdon** [AstrOOnauta/react-native-international-phone-number#31]
Hi :)

This package is so great, and thank you, @AstrOOnauta, I just want to signal this little thing

Incorrect mask phone number for Madagascar country => phoneMasks: ['## ## #####']
Correct phone mask is => phoneMasks: ['## ## ### ##']

![image](https://github.com/AstrOOnauta/react-native-international-phone-number/assets/46904458/e92dfa3e-fb64-49ec-bfae-7ad4e63fbfa6)

**Comment by AstrOOnauta** [comment]
Hey @PaulOdon, thanks for your correction!! 

I fixed this case...its will be up on new version soon =)

🚀 AstrOOnauta 🚀

**Comment by PaulOdon** [comment]
Thanks a lot @AstrOOnauta

**Comment by AstrOOnauta** [comment]
@PaulOdon I released a new version with your contribution...thanks!

So, please update your lib to latest `v0.6.6`

🚀 AstrOOnauta 🚀

**Comment by PaulOdon** [comment]
Nice, 
Thanks a lot @AstrOOnauta
