### ISSUE TITLE
Can I remove very heavy font TwemojiMozilla?

### ISSUE THREAD

**Issue by SergiOnGit** [AstrOOnauta/react-native-international-phone-number#32]
This font is 1.2MB which is very big, why is it needed and can I remove or replace it?

**Comment by AstrOOnauta** [comment]
Hey @SergiOnGit good question!

For now, I need that font to display the flags icons in all platforms (RN Web, for example). So, if you have any solutions to this...please, share with us =)

🚀 AstrOOnauta 🚀

**Comment by SergiOnGit** [comment]
> Hey @SergiOnGit good question!
> 
> For now, I need that font to display the flags icons in all platforms (RN Web, for example). So, if you have any solutions to this...please, share with us =)
> 
> 🚀 AstrOOnauta 🚀

You can just include all country flag icons, maybe png. One flag icon can be max 2KB. So, It will be much smaller.

**Comment by AstrOOnauta** [comment]
@SergiOnGit  I released a new version fixing this point: font TwemojiMozilla.ttf (1.2MB) to TwemojiMozilla.woff2 (0.4MB)

So, please update your lib to latest v0.6.7

🚀 AstrOOnauta 🚀

**Comment by SergiOnGit** [comment]
That's great! Thanks.

**Comment by ethras** [comment]
I'm facing issue with .woff2 font in expo. I get an "sha-1 for file is not computed" when trying to load the font

**Comment by AstrOOnauta** [comment]
@ethras try to put the font file inside `assets` name of folder something like the [snack](https://snack.expo.dev/@astroonauta/react-native-international-phone-number) example. Some versions of expo and RN cli can happen this throuble.

**Comment by AstrOOnauta** [comment]
@ethras try to put the font file inside `assets` name of folder something like the [snack](https://snack.expo.dev/@astroonauta/react-native-international-phone-number) example.

**Comment by ser-emejia** [comment]
> @ethras try to put the font file inside `assets` name of folder something like the [snack](https://snack.expo.dev/@astroonauta/react-native-international-phone-number) example.

I'm having issues, I can't load the font, I did what you mention here but does not work

**Comment by AstrOOnauta** [comment]
@ser-emejia what is your issue? please, try to open a new issue with more details...

**Comment by ser-emejia** [comment]
> @ser-emejia what is your issue? please, try to open a new issue with more details...

Of course man 👍
