### ISSUE TITLE
getCountriesByCallingCode is returning undefined for some codes.

### ISSUE THREAD

**Issue by mittal-rupali** [AstrOOnauta/react-native-international-phone-number#35]
Used calling code +1684, getCountriesByCallingCode is returning undefined. Same code is displayed by the flag picker.

**Comment by AstrOOnauta** [comment]
@mittal-rupali sorry about this...

I fixed this issue on the next version...so, please, update your lib react-native-international-phone-number to v0.6.8 and enjoy...

🚀 AstrOOnauta 🚀
