### ISSUE TITLE
[QUESTION] - Is there a way to add an icon next to the flag icon?

### ISSUE THREAD

**Issue by ser-emejia** [AstrOOnauta/react-native-international-phone-number#38]
Hello, first thanks for your work, it's an amazing library.

Is possible to add an icon next to the flag icon? for example, I would like to add an arrow down, something like this:

<img width="268" alt="Screenshot 2023-11-29 at 7 43 32 a m" src="https://github.com/AstrOOnauta/react-native-international-phone-number/assets/99516008/2c6a9094-fb3f-4ab0-9764-8d2beef597a8">

Thank you! 🚀

**Comment by ser-emejia** [comment]
> @ser-emejia not for now..but I will soon! Thanks for this insight...

Thank you, It would be nice! 🚀

**Comment by AstrOOnauta** [comment]
@ser-emejia I released a new version with your insight...thanks!

So, please update your lib to latest v0.7.0

🚀 AstrOOnauta 🚀
