### ISSUE TITLE
Issue load TwemojiMozilla font

### ISSUE THREAD

**Issue by ser-emejia** [AstrOOnauta/react-native-international-phone-number#39]
After update my project to new version `v0.6.7` I'm facing issues to load the font, see screenshot bellow:

![Screenshot 2023-11-29 at 9 54 37 a m](https://github.com/AstrOOnauta/react-native-international-phone-number/assets/99516008/2772e157-9e67-4752-97ec-e93e9c805a6b)

[I followed this suggestion](https://github.com/AstrOOnauta/react-native-international-phone-number/issues/32#issuecomment-1828073936) but it does not work.

Thank you for your help!

**Comment by AstrOOnauta** [comment]
Hey @ser-emejia

Are you using Expo, right? Do you followed the [lib documentation](https://github.com/AstrOOnauta/react-native-international-phone-number#additional-config) and installed the dependency `expo-font` to load the font `TwemojiMozilla`??
See the official documentation [here](https://docs.expo.dev/develop/user-interface/fonts/#use-a-custom-font) about custom fonts with Expo or see [my example](https://snack.expo.dev/@astroonauta/react-native-international-phone-number) and follow it.

Please, let me know if this dont fix your issue...

🚀 AstrOOnauta🚀

**Comment by ser-emejia** [comment]
> lib documentation

Yes, I'm using expo, I followed the documentation as you mentioned but same result:

![Screenshot 2023-11-29 at 12 02 48 p m](https://github.com/AstrOOnauta/react-native-international-phone-number/assets/99516008/bdeda9c6-52f7-4f6f-854b-eade0192afcd)

I load the font in that way:

```
export const customFonts = {
...mycustomfonts,
  TwemojiMozilla: require('../../node_modules/react-native-international-phone-number/lib/assets/fonts/TwemojiMozilla.woff2'),
};

```

**Comment by AstrOOnauta** [comment]
@ser-emejia can you put the font `TwemojiMozilla` (from lib) inside a folder called `assets` on root of your project (like the [example](https://snack.expo.dev/@astroonauta/react-native-international-phone-number))? Sometimes the Expo has conflicts with this...

**Comment by ser-emejia** [comment]
Same result, I downloaded the font and to my `assets` folder, but the problem is the same:

`Unable to resolve "../../assets/fonts/TwemojiMozilla.woff2" from "src/utils/index.ts"`

By the way, 

[checking expo documentation](https://docs.expo.dev/develop/user-interface/fonts/#beyond-otf-and-ttf) I noticed that `wff2` font is not supporting by Android

**Comment by AstrOOnauta** [comment]
@ser-emejia Im studying a solution for you case..sorry about this :X

**Comment by AstrOOnauta** [comment]
@ser-emejia I released a new version fixing this issue! The TwemojiMozilla font will be necessary only to Web version now..

You dont need more load this font to Android or iOS (only Web version now).
So, please update your lib to latest v0.7.0.

Please, let me know if this fix your trouble...

🚀 AstrOOnauta 🚀

**Comment by ser-emejia** [comment]
Thank you so much for your help and time, it works now on expo, in both, iOS and Android 🚀

**Comment by agrittiwari** [comment]
It's been some time, but I am seeing the same error while loading the font for web.
@AstrOOnauta  I am running react native web. and it breaks. Is there something missing?
