### ISSUE TITLE
Cant change caret style

### ISSUE THREAD

**Issue by pedrogarciyalopez** [AstrOOnauta/react-native-international-phone-number#42]
I want to hide the caret, but when I add styles for the caret, the caret is duplicated. This happens even if you add just an empty object.
```
caret: {
    display: 'none',
  },
```
<img width="122" alt="image" src="https://github.com/AstrOOnauta/react-native-international-phone-number/assets/14232660/607edfee-0a62-4864-b004-143e663d7f16">

**Comment by AstrOOnauta** [comment]
@pedrogarciyalopez sorry about this...I will crrect this

But, for bow...you can hide the caret following the next code:

```
caret:{
 fontSize: 0.1
}
```

**Comment by pedrogarciyalopez** [comment]
@AstrOOnauta thank you for quick reply. `fontSize: 0.1` helps but there is a barely noticeable dot on the retina-display, it would be great if you could fix the caret styles.

**Comment by AstrOOnauta** [comment]
@pedrogarciyalopez sorry for my late..

I release a new version fixing this issue. So, please, update your lib for the latest version `v.0.7.2`.

🚀 AstrOOnauta 🚀
