### ISSUE TITLE
Unable to use default value

### ISSUE THREAD

**Issue by leviFrosty** [AstrOOnauta/react-native-international-phone-number#46]
There are two weird edge cases that I'm running into:

1. I'm unable to pass a value default value from state
```tsx
  const [value, setValue] = useState("8885551234");
  // component does not render with 8885551234
```

2. onChangePhoneNumber runs at component mount
I believe onChangePhoneNumber should have the same functionality as TextInput onChangeText, which does _not_ get called on mount.
I believe this is having the unintended effect that when it's called on mount, the value initially is "", so it's overriding the initial value passed into the component.

Repro: https://snack.expo.dev/@levi_frosty/react-native-international-phone-number

I'm happy to open a PR or help fix this if this is something you'd like for me to do, or if you want to fix it yourself. Please let me know. Thanks for the help on this and your work.

**Comment by AstrOOnauta** [comment]
Hey @leviFrosty you can use the props `defaultValue` to set a default value to input...
Check the example:
```
<PhoneInput
        theme="dark"
        defaultValue="+5511999999999"  <-- Add this (
        value={inputValue}
        onChangePhoneNumber={handleInputValue}
        selectedCountry={selectedCountry}
        onChangeSelectedCountry={handleSelectedCountry}
 />
```
Read the next point in the [docs](https://github.com/AstrOOnauta/react-native-international-phone-number#default-phone-number-value) for more details.

🚀 AstrOOnauta 🚀

**Comment by leviFrosty** [comment]
@AstrOOnauta,

After looking into this further, your defaultValue fix worked. 

However, I think the api documenation could benefit from mentioning it needs [e164](https://en.wikipedia.org/wiki/E.164) phone format.

Please consider adding!

Thanks.

Aside: onChangePhoneNumber still runs at component mount, I believe this is a bug.

**Comment by AstrOOnauta** [comment]
@leviFrosty thanks dor your contribution..I didnt know this format `e164`...I will add to documentation soon...

About the `onChangePhoneNumber`, is not a bug...let's say it's part of its current operation (but I will consider studying a better solution for this behavior in the future)...

🚀 AstrOOnauta 🚀

**Comment by leviFrosty** [comment]
Thanks for your help.

**Comment by leviFrosty** [comment]
I want to reopen this actually. I should not be forced to pass a valid number into the default value. Currently only valid e164 formatted numbers will be allowed.

Let me give an example:

- A user may type in a bad phone number
- They save the data
- They go to edit their phone number later, the app autofills their bad data (for them to fix)
- They can't autofill the bad phone number because it doesn't allow non-e164 formats.

I think if the format is not recognized, it should use the defaultCountryCode prop for the country code, else, it defaults to +1 or some specific country that you decide.

Thoughts?

**Comment by AstrOOnauta** [comment]
@leviFrosty  You need to save the `callingCode` together with the user's phone number

So, with the callingCode and the phone number (wrong or not) of the user data... you can create the phone format `e164`...

I use it like this...


🚀 AstrOOnauta 🚀
