### ISSUE TITLE
Search input modal ( selection color )

### ISSUE THREAD

**Issue by aleksavucenovic** [AstrOOnauta/react-native-international-phone-number#49]
Is it possible to add a **selectionColor** for the **search input modal**?

**Comment by AstrOOnauta** [comment]
@aleksavucenovic I think that yes!
You need to make changes on iOS and Android native files...
Read a solution [here](https://stackoverflow.com/a/63409904) and let me know if this work...

🚀 AstrOOnauta 🚀

**Comment by aleksavucenovic** [comment]
I'm only using Expo, so I guess I'll have to wait for an enhancement 🙂

**Comment by AstrOOnauta** [comment]
@aleksavucenovic Sorry for my late

I release a new version fixing this issue. So, update your lib for the latest version v.0.7.5.

Let me know if your problem continues...

🚀 AstrOOnauta 🚀

**Comment by aleksavucenovic** [comment]
Now the selection color is black by default.
Where should I define the property for (modal input selection color)?

I have selectionColor="red" defined inside PhoneInput which works for input number, but not for modal input.

**Comment by AstrOOnauta** [comment]
@aleksavucenovic you need add the props `modalSearchInputSelectionColor` to `PhoneInput` component. See the example:

```
...
<PhoneInput
...
modalSearchInputSelectionColor="red"
/>
```

If you need change de placehold color, add the props `modalSearchInputPlaceholderTextColor`.

🚀 AstrOOnauta 🚀

**Comment by aleksavucenovic** [comment]
Thank you very much, it works great :))
