### ISSUE TITLE
Position of modal

### ISSUE THREAD

**Issue by harundogan01** [AstrOOnauta/react-native-international-phone-number#50]
Hi,

I want to fix modal at the center of screen. How I can do this?

![image](https://github.com/AstrOOnauta/react-native-international-phone-number/assets/100342868/cef0934e-b56d-4496-baf8-bedb0ce8f4a1)

I couldn't see a style feature about this in the documentation. Even if I gave Position: 'center' it didn't work.

Thanks

**Comment by AstrOOnauta** [comment]
@harundogan01 check this [comment](https://github.com/AstrOOnauta/react-native-international-phone-number/issues/34#issuecomment-1826225285).

🚀 AstrOOnauta 🚀
