### ISSUE TITLE
Add Kosovo to the list or add opportunity to add custom countries via props

### ISSUE THREAD

**Issue by klendi** [AstrOOnauta/react-native-international-phone-number#53]
I see that Kosovo (+383) isn't added to the list. If possible to add that or you can add new props to extend existing countries ourselves please.

**Comment by klendi** [comment]
Sure, it's : +383 XX XXX XXX

**Comment by klendi** [comment]
I would suggest to add a prop to extend the countries list since I think there are some others missing too. Small countries

**Comment by AstrOOnauta** [comment]
@klendi unfortunally, this is not possible...the countries are update into a json file and in the country picker modal lib...

Soon, I will add the country Kosovo...
If you notice any other countries, please let me know...

🚀 AstrOOnauta 🚀
