### ISSUE TITLE
Keyboard pad not closing despite clicking outside the pad.

### ISSUE THREAD

**Issue by izner32** [AstrOOnauta/react-native-international-phone-number#57]
It's a problem for iOS since it doesn't have the 'Done' button unlike in Android.

**Comment by izner32** [comment]
One workaround I have done is to wrap the entire component with TouchableWithoutFeedback which dismisses keyboard when clicked.

**Comment by AstrOOnauta** [comment]
Hey @izner32 ...you need add some methods on click on keypad backdrop

Please, check https://github.com/AstrOOnauta/react-native-international-phone-number/issues/15#issuecomment-1730071114 and https://github.com/AstrOOnauta/react-native-international-phone-number/issues/15#issuecomment-1730530503.

🚀 AstrOOnauta 🚀
