### ISSUE TITLE
How to handle country specific phone number variations ? (ex: prefix zero in some countries)

### ISSUE THREAD

**Issue by gkpo** [AstrOOnauta/react-native-international-phone-number#58]
In France for instance, phone numbers are usually written as:
`06 65 11 22 33`
The valid equivalent to this number is:
`+336 65 11 22 33`

Now with react-native-international-phone-number if a user selects France as a country, it will automatically prefix `+33` in front of the number. However, not everybody will know that they have to remove the zero prefix when they see `+33`.
So in my case, I sometimes end up with this number being saved to the database: 
`+3306 65 11 22 33`

Is there a way to handle this kind of country specific variations in user input ? I don't know what variations exist in each country so I'm wondering if this library has something doing this.

I think ideally it would detect that a zero has been inserted, and put it in parenthesis like so:
`+33(0)6 65 11 22 33` -> On the user interface
`+336 65 11 22 33` -> Saved to the DB

**Comment by AstrOOnauta** [comment]
Hey @gkpo! Thanks for your issue, an interesting point that I wasn't aware of...
I will think about a solution soon...

But, for now..you can remove the `0` (usying `substring` method) if the phoneNumber started with `0` before saving to your DB.

🚀 AstrOOnauta 🚀

**Comment by gkpo** [comment]
Yes, that's what I ended up doing :) thanks for your work!

**Comment by Bilal-Abdeen** [comment]
@AstrOOnauta Thank you for the great library. I would like to add my vote to implement the option to remove zeros inserted between the country code and the local phone number. Some other libraries provide this feature as a method. 

Example 1: 
https://github.com/thegamenicorus/react-native-phone-input/blob/43d935639a7806b25a9fef15be6c9f6fcd8c88b4/lib/index.js#L166

Example 2: 
https://github.com/garganurag893/react-native-phone-number-input/issues/20#issuecomment-1975505529

**Comment by Bilal-Abdeen** [comment]
Thank you for adding the property `allowZeroAfterCallingCode`. However, I am not sure how it works!?

When this property is set to `true`, I expected `onChangePhoneNumber` to remove the leading zero before sending the value to the relevant callback function. Example: 
```javascript
<PhoneInput
   allowZeroAfterCallingCode={true}
   value={state.phoneNo} 
   onChangePhoneNumber={(value) => {
       console.log("value:", value, ); // value should NOT include the leading zero 
       // ......
   }}
/>
```

Moreover, I expected the mask to allow a leading zero, in addition to the significant digits. So, mask would allow `0123` and `123`. 

For users reading this, I use a workaround by specifying a custom mask `customMask={[ "04## ### ###", "4## ### ###", ]}`, and removing the leading zero manually inside the callback function.

**Comment by AstrOOnauta** [comment]
Hey @Bilal-Abdeen, sorry for my late.

The props allowZeroAfterCallingCode works like you send me in this [comment](https://github.com/AstrOOnauta/react-native-international-phone-number/issues/58#issuecomment-1975586626) (Example 1).
So, if this props  is TRUE ...the mask allow `0123` and `123`. But is  this props is FALSE, the mask allow only 123 (without 0 after the calling code).

I release a new version with this solution. So, please, update your lib for the latest version v.0.8.1.

Let me know if this solve your issue.

🚀 AstrOOnauta 🚀

**Comment by Bilal-Abdeen** [comment]
@AstrOOnauta Thank you for the change. Setting this property affects the value sent to the callback `onChangePhoneNumber`. This is good. 

However, it seems that the masks defined in the library do NOT know that they need to accept a prefix of zero! In effect, the mask wrongly shortens the allowed number of digits. Please check the example below. 

Using the default country `US` and using `allowZeroAfterCallingCode={true}` 
user enters the phone number: `0123 456 7891`
the component wrongly masks the value to: `0123 456 789` - the last digit is removed

I had to go back to the previous release. With this release, my workaround (below) does NOT work any more! :( 
1. using custom mask `customMask={[ "04## ### ###", "4## ### ###", ]}`, and 
2. removing the leading zero manually inside the callback function.

**I strongly suggest un-publishing this release `0.8.1`.**

**Comment by AstrOOnauta** [comment]
Now, I understand your point @Bilal-Abdeen !!
I will fix it soon..sorry about that.

**Comment by AstrOOnauta** [comment]
Hey @Bilal-Abdeen, I release a new version with a new solution. So, please, update your lib for the latest version v.0.8.2 and let me know if this solve your issue.

Now, the props `allowZeroAfterCallingCode` is `true` by default.

🚀 AstrOOnauta 🚀

**Comment by Bilal-Abdeen** [comment]
@AstrOOnauta It works perfectly!
However, it seems that `cusomMask` property does NOT work anymore!? The correct mask for Australian mobile numbers follows. It stopped working. The default mask (from the library) is used, and my custom mask is ignored. 
`customMask={[ "04## ### ###", "4## ### ###", ]}`

**Comment by Bilal-Abdeen** [comment]
@AstrOOnauta It works perfectly!

However, this can be considered **a breaking change!** I suggest clarifying this in the readme file. 

To allow a prefix of zero, my code was using `customMask={[ "04## ### ###", "4## ### ###", ]}` as a workaround . This stopped working. For my code to work with the use of the new `allowZeroAfterCallingCode`, I need to use  `customMask={[ "4## ### ###", ]}`. It seems that the prefix of a zero cannot be used in the mask anymore. 

By the way, the correct mask for Australian mobile phone numbers is "4## ### ###", and not the one in the library .

**Comment by AstrOOnauta** [comment]
It's good to know that this has been resolved @Bilal-Abdeen !

I will think about in your suggest to README file, nice point.

And I will fix the Australian mobile phone number mask, thanks...next version this will be up!

🚀 AstrOOnauta 🚀
