### ISSUE TITLE
Invalid mask for Zimbabwean phone numbers

### ISSUE THREAD

**Issue by fbele** [AstrOOnauta/react-native-international-phone-number#59]
Currently Zimbabwean mask for phone numbers is as such: '# ######', but it should be like this: '## ### ####'.
Is it possible that you update this with the next release? Thanks.

**Comment by AstrOOnauta** [comment]
Hey @fbele thanks for your contribution...
That will be on the next realease yeah!

🚀 AstrOOnauta 🚀

**Comment by fbele** [comment]
> Hey @fbele thanks for your contribution... That will be on the next realease yeah!
> 
> 🚀 AstrOOnauta 🚀

Sorry, I actually gave you wrong mask. The proper one is this: '### ### ###'.
