### ISSUE TITLE
Suggestion: maxLength for Phone Number Input

### ISSUE THREAD

**Issue by KushaanKapoor** [AstrOOnauta/react-native-international-phone-number#6]
HI, I really like this library, but I cannot find the option to increase the number of digits as input available.

Since there are alot of countries that accept 11 numbers and more, rather than 10. this seems like an issue which users might face when trying to enter their phone number for authentication.

I would like to increase the number of digits accepted in the phone number input.

**Comment by AstrOOnauta** [comment]
Hey @KushaanKapoor !

I see your PR about this discussion and I apreciate it.
So, I realease a new version with your contribute.

Please, update your `react-native-international-phone-number` lib to version `0.4.15` and enjoy!

Thanks,
🚀 AstrOOnauta 🚀

**Comment by Kushaan-Kz** [comment]
That's great! Thanks a lot @AstrOOnauta. I look forward to this library.
