### ISSUE TITLE
Font scaling

### ISSUE THREAD

**Issue by matheusbento** [AstrOOnauta/react-native-international-phone-number#60]
It's possible to disable font scaling and pass the maxFontSizeMultiplier inside the input??

Specially the country input

I'm having issue:

<img width="355" alt="image" src="https://github.com/AstrOOnauta/react-native-international-phone-number/assets/13539594/1046159c-0426-465c-afaa-d7487c66df78">

**Comment by AstrOOnauta** [comment]
@matheusbento can you send me any example about this? I didn't understand much about it...

**Comment by AstrOOnauta** [comment]
No more answers...Im closing this issue...
