### ISSUE TITLE
Error when using Ref and useState at the same time 

### ISSUE THREAD

**Issue by rodrigodiasf1984** [AstrOOnauta/react-native-international-phone-number#61]
Hi a@astrOOnauta, thanks for this package. 

How can I handle this error? 

![image](https://github.com/AstrOOnauta/react-native-international-phone-number/assets/30758309/0f710441-7cdd-4e46-a583-45e9cbfdbae3)

Thx

**Comment by AstrOOnauta** [comment]
Hey @rodrigodiasf1984.

On docs, I warn you that you can't use both (state nad ref). Please, check [this session](https://github.com/AstrOOnauta/react-native-international-phone-number?tab=readme-ov-file#react-hook-form--typescript--default-phone-number-value] when to use react-hook-form lib and [this session](https://github.com/AstrOOnauta/react-native-international-phone-number?tab=readme-ov-file#typescript--useref) when you will use ref.

🚀 AstrOOnauta🚀

**Comment by rodrigodiasf1984** [comment]
Hey @AstrOOnauta , thanks for your answer,  I  saw that in the documentation, but how can I manage the onSubmited editing if I can use the ref? There is another way?

**Comment by AstrOOnauta** [comment]
@rodrigodiasf1984 you can add the `onSubmitEditing` normally...see the follow example (I tested...and wokr fine):

```
import React, { useRef } from 'react';
import { View, Text, TouchableOpacity, Alert } from 'react-native';
import PhoneInput, {
} from 'react-native-international-phone-number';

export default function App() {
  const phoneInputRef = useRef();

  function onSubmitRef() {
    Alert.alert(
      'Intermediate Result',
      `${phoneInputRef.current?.selectedCountry?.callingCode} ${phoneInputRef.current?.value}`
    );
  }

  return (
    <View style={{ width: '100%', flex: 1, padding: 24 }}>
      <PhoneInput ref={phoneInputRef} onSubmitEditing={onSubmitRef} />
      <TouchableOpacity
        style={{
          width: '100%',
          paddingVertical: 12,
          backgroundColor: '#2196F3',
          borderRadius: 4,
          marginTop: 10,
        }}
        onPress={onSubmitRef}
        
      >
        <Text
          style={{
            color: '#F3F3F3',
            textAlign: 'center',
            fontSize: 16,
            fontWeight: 'bold',
          }}
        >
          Submit
        </Text>
      </TouchableOpacity>
    </View>
  );
}
```

🚀 AstrOOnauta🚀

**Comment by brajmohan-nimblechapps** [comment]
@AstrOOnauta I need to show real-time errors based on state changes, so I didn't use a ref. Now, How can I focus on a specific phoneInput from another input field while using state?
