### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by michaelpautov** [AstrOOnauta/react-native-international-phone-number#65]
countries.js
line: 3338
ru: 'Kyrgyzstan' to ru: 'Кыргызстан',

**Comment by sudhanshuku01** [comment]
Can i make full request by changing it ?

**Comment by AstrOOnauta** [comment]
Hey @michaelpautov  , Thanks for your contribution! Next version this will be up.

**Comment by AstrOOnauta** [comment]
I release a new version fixing this issue. So, please, update your lib for the latest version v.0.8.1.

🚀 AstrOOnauta 🚀
