### ISSUE TITLE
In RTL mode, phone input element should display LTR

### ISSUE THREAD

**Issue by Bilal-Abdeen** [AstrOOnauta/react-native-international-phone-number#68]
Thank you very much for the excellent library! 

Phone numbers (like any number) should be written LTR (Left-to-Right) regardless of the language. 

In the component of this library, in RTL (Right-to-Left) mode, the country code (and flag) are displayed on the right side and the phone number on the left side of the screen. This is caused by the auto swapping of components done by the React-Native RTL support. I suggest adding a prop to reverse the auto swapping.

![phone_input](https://github.com/AstrOOnauta/react-native-international-phone-number/assets/8470766/26ede966-250e-4dc3-8e5b-b4044db20356)

**Comment by PPHelios** [comment]
I have same issue, using textInput solves the reversed numbers but for me in rtl the input is on the left and country selector is on the right, is there a way to force the component to keep ltr layout?

**Comment by Bilal-Abdeen** [comment]
@PPHelios
@AstrOOnauta implemented my PR, which fixes the problem I demonstrated in the image above. Try using the latest version. 

@PPHelios
I have created a different #70 issue for reversing the digits while entering the number.
