### ISSUE TITLE
Croatia's mask is wrong, it should be ### ### ### and not the current ## ### ###

### ISSUE THREAD

**Issue by MatkoMilic** [AstrOOnauta/react-native-international-phone-number#76]
Hello, I am Croatian so I know that every mobile number in Croatia has ### ### ### , using this library I cant enter the last digit of mine or any Croatian number, current mask for Croatia is wrong (## ### ###).

**Comment by MatkoMilic** [comment]
Of course that can be fixed by editing countries.js file and thats what I did.

**Comment by AstrOOnauta** [comment]
@MatkoMilic Thanks for your contribution! Next version this will be up.
