### ISSUE TITLE
Styling State

### ISSUE THREAD

**Issue by Keenan-Softserve** [AstrOOnauta/react-native-international-phone-number#77]
Hi there, thank you for your library :)

Can you please look at allowing styling of the container when it's active (i.e user clicks on the input to start typing). 

I'm using react-native-paper so I would've liked props such as 'textColor', 'outlineColor', 'activeOutlineColor', etc.

If anyone knows a work-around to apply styles to the container when it is active, please let me know :)

**Comment by AstrOOnauta** [comment]
Please, check the section [Customizing lib](https://github.com/AstrOOnauta/react-native-international-phone-number?tab=readme-ov-file#customizing-lib). 
Idea: you can get the focused status usying the TextInput methods onFocus and onBlur nad manage this state to render differents styles objects for actived/deactived.
