### ISSUE TITLE
when keyboard open search doesnt show up 

### ISSUE THREAD

**Issue by egecetiner** [AstrOOnauta/react-native-international-phone-number#85]
My modal height is 90% and when i open focus search input keyboard padding make search lose. i should be able to close keyboard padding.

**Comment by AstrOOnauta** [comment]
Please send me more information about this, like a video, for investigation.

**Comment by AstrOOnauta** [comment]
I could not reproduce it. As I haven't had any more answers about this case, I'm closing this issue.
