### ISSUE TITLE
onChangePhoneNumber called with empty string on first render

### ISSUE THREAD

**Issue by dufourgilles** [AstrOOnauta/react-native-international-phone-number#87]
When PhoneInput is rendered the first time, it does emit a onChangePhoneNumber('').
This is caught by my React component which then believes the input was reset.
This comes from code at line 244 of lib/index.js ... commenting that line does fix the issue.
Any reason for that line ?

![image](https://github.com/user-attachments/assets/10b6cb39-d34a-47ba-baef-5744e28db89b)

**Comment by AstrOOnauta** [comment]
Hello @dufourgilles this is how the lib work at the moment. It force the input field empty on the start, if you dont use a default value.
