### ISSUE TITLE
Phone Number input not allowing to add extra number

### ISSUE THREAD

**Issue by ezcubic** [AstrOOnauta/react-native-international-phone-number#89]
This would be an issue to some specific regions. My local phone number has 10 numbers excluding the country code but the phoneInput only allows me to enter 9 numbers, this was detected when I used MY as my defaultCountry, please help on this issue

**Comment by ezcubic** [comment]
Additional information, I did try the maxLength on the phoneInput but it did not allow me to add my extra number

**Comment by AstrOOnauta** [comment]
Hi @ezcubic , please send me the correct mask for your country (like XXX XXX XXXXX) and I will update this on future.

An alternative for you is to use the prop [CustomMask](https://github.com/AstrOOnauta/react-native-international-phone-number/tree/master?tab=readme-ov-file#custom-phone-mask) for now.

**Comment by vyashya12** [comment]
Hi @AstrOOnauta, I think the correct mask for MY Malaysia is either XXX XXXX XXXX if 11 numbers or XXX XXX XXXX if 10 numbers. ok I will look into the CustomMask, thank you for your help @AstrOOnauta

**Comment by vyashya12** [comment]
I can already input Malaysia Numbers using the mask, thanks @AstrOOnauta.
I'm gonna close this issue
