### ISSUE TITLE
Hide the country code next to the flag

### ISSUE THREAD

**Issue by rnwonder** [AstrOOnauta/react-native-international-phone-number#9]
Hey great library. I was wondering if there is a prop to hide the country code next to the flag. both on the modal and on the input. Really would appreciate being able to hide it on the input.

**Comment by AstrOOnauta** [comment]
Hi @rnwonder !

Thanks for using the lib and sorry for the delay in replying.

So, there is none way to you do this (directly).
But, in the v0.5.0, you can use the props `flagTextStyle` to hide the calling code (country code) next to the main flag (not inside the modal, there's no way...not for now). See the example:

```
import PhoneInput from 'react-native-international-phone-number';

...

<PhoneInput
   ...
   flagTextStyle={{display: "none"}}   <------- ADD THIS
/>
```
I hope it's useful in your case, and I'll think more about how to implement the feature you requested.

🚀 AstrOOnauta 🚀

**Comment by AstrOOnauta** [comment]
@arirah

Now, you can hide the calling code inside the modal (usying the props modalStyle), too. To read more about this, visit the [documentation](https://github.com/AstrOOnauta/react-native-international-phone-number#custom-lib-styles).

See the example:

import PhoneInput from 'react-native-international-phone-number';

```
...

<PhoneInput
   ...
   flagTextStyle={{display: "none"}}
   modalStyle={{
     callingCode: {
        display: "none"
      },
   }}
/>
```

Please, update the lib react-native-international-phone-number to v0.5.3 and enjoy.

🚀 AstrOOnauta 🚀
