### ISSUE TITLE
Korean phone number mask is wrong, misses one character

### ISSUE THREAD

**Issue by kyujonglee** [AstrOOnauta/react-native-international-phone-number#91]
I am truly grateful for your project. 😎

Could you change the phone masks for +82 South Korea as follows?

phoneMasks: ['## ### ####'] -> ['## #### ####']

**Comment by kyujonglee** [comment]
Any update? 🥹

**Comment by AstrOOnauta** [comment]
Hey @kyujonglee  thanks for your contribution!
Next version this will be up.
