### ISSUE TITLE
Wrong mask for Gambian phone numbers

### ISSUE THREAD

**Issue by ebrimasamba** [AstrOOnauta/react-native-international-phone-number#92]
Hi I love this library, saved me a bunch of time.

I noticed the Mask for my country "Gambia" is wrong, it currently has "### ## ##" instead of "### ####". for eg. this a what a gambian number looks like (220) 314 2175.

Thank you in advance, Keep up the great work!!!!!!

**Comment by AstrOOnauta** [comment]
Hey @kyujonglee  thanks for your contribution!
Next version this will be up

🚀 AstrOOnauta 🚀

**Comment by AstrOOnauta** [comment]
I release a new version fixing this issue. So, please, update your lib for the latest version v.0.8.1.

🚀 AstrOOnauta 🚀

**Comment by ebrimasamba** [comment]
You're the best. Thanks
