### ISSUE TITLE
Default Value causing callingCode crash

### ISSUE THREAD

**Issue by RyanMurphyMobi** [AstrOOnauta/react-native-international-phone-number#98]
When trying to set the default value of GB +44 it is causing a cash saying the callingCode is undefined. 

I have checked and the phone number is in the correct format. 

Edit: Here is the phone number +447999548129

**Comment by AstrOOnauta** [comment]
Sorry about this @RyanMurphyMobi . I fixed this and next version this will be up...

**Comment by AstrOOnauta** [comment]
I release a new version fixing this issue. So, please, update your lib for the latest version v.0.8.4.

🚀 AstrOOnauta 🚀
