### ISSUE TITLE
An invalid or illegal string was specified

### ISSUE THREAD

**Issue by Pukimaa** [AstrOOnauta/react-native-international-phone-number#99]
I get these errors when using the typescript example (basic usage with useState) from the Readme:
```
An invalid or illegal string was specified
```
![error source](https://github.com/user-attachments/assets/f99f118d-19a6-4384-af25-a39460419070)

**Comment by AstrOOnauta** [comment]
Hey @Pukimaa 
You config typescript in your project? Because according to the error, the “string” was not specified..

**Comment by Pukimaa** [comment]
> Hey @Pukimaa You config typescript in your project? Because according to the error, the “string” was not specified..

Yes I did.

**Comment by Pukimaa** [comment]
Also string is specified. Just an invalid one provided, but I didn't do anything, but click on the country dropdown.

**Comment by AstrOOnauta** [comment]
@Pukimaa  I dont have idea what is wrong, can you upload your code in anywhere?

Because, I tested here and work right, look the code:
![image](https://github.com/user-attachments/assets/61d52210-5b61-4cca-8744-6b30c59879da)

**Comment by AstrOOnauta** [comment]
I release a new version fixing this issue. So, please, update your lib for the latest version v.0.8.4.

🚀 AstrOOnauta 🚀

**Comment by Pukimaa** [comment]
Thank you so much! Sorry for not responding. Will check whether this works now in a few hours :)

**Comment by AstrOOnauta** [comment]
Sorry @Pukimaa ! I sent an wrong message before..your case remains under analysis :/

**Comment by Pukimaa** [comment]
Oh alright. Since the code is closed source I can't really show much. Will try to get the most important part related to the phone number input later :)

**Comment by Pukimaa** [comment]
I cannot reproduce the error anymore. While it still does not work it seems to be related to our styling engine (Unistyles v3), since the new error talks about unistyles failing to inject styling. I'll open an issue there now and reopen this one, if it can only be fixed by you :)
